# Generated by Django 3.1.1 on 2020-09-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(max_length=50, null=True)),
                ('temperature', models.FloatField(null=True)),
            ],
        ),
    ]
