# Generated by Django 3.1.1 on 2020-09-29 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='result',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
