# Generated by Django 3.1.1 on 2020-10-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_symptoms_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
